image: naveenkrsh/gradle-nodejs-12-jdk-11:v0.3

before_script:
  - chmod +x ./gradlew

package:
  stage: build
  script:
    - ./gradlew assemble
  only:
    - master
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "front-development"

test-back:
  stage: test
  script:
    - ./gradlew test
  only:
    - master
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "front-development"

test-front:
  stage: test
  script:
    - cd src/main/webapp
    - npm install
    - npx jest --coverage
    - cd ../../..
    - ./gradlew sonarqube
  only:
    - master
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "development"

#deploy:
#  variables:
#    USERNAME: dlinevich
#    PASSWORD: KLmiE=Sc)6%csVn
#    REPOSITORY: calorie-meter
#  stage: deploy
#  script:
#    - curl -u $USERNAME:$PASSWORD -X "DELETE" https://cloud.docker.com/v2/repositories/$USERNAME/$REPOSITORY/tags/back/
#    - curl -u $USERNAME:$PASSWORD -X "DELETE" https://cloud.docker.com/v2/repositories/$USERNAME/$REPOSITORY/tags/front/