image: gradle:jdk11

before_script:
  - chmod +x ./gradlew

package:
  stage: build
  script:
    - ./gradlew assemble
  only:
    - master
    - merge_requests

test:
  stage: test
  script:
    - ./gradlew test
  only:
    - master
    - merge_requests
