image: naveenkrsh/gradle-nodejs-12-jdk-11:v0.3

before_script:
  - chmod +x ./gradlew
  - export DOCKER_HOST="${HOSTNAME}-docker"

package:
  stage: build
  script:
    - ./gradlew assemble
  only:
    - master
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "front-development"

test-back:
  stage: test
  script:
    - ./gradlew test
  only:
    - master
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "front-development"

test-front:
  stage: test
  script:
    - cd src/main/webapp
    - npm install
    - npx jest --coverage
    - cd ../../..
    - ./gradlew sonarqube
    - ls
  only:
    - master
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "development"

deploy:
  image: docker:latest
  services:
    - docker:dind
  variables:
    USERNAME: dlinevich
    PASSWORD: KLmiE=Sc)6%csVn
    REPOSITORY: calorie-meter
  stage: deploy
  script:
    - ls
    - docker build -t caloriesmeter_back -f docker/Dockerfile .
    - docker build -t caloriesmeter_front -f docker/front/Dockerfile .
    - docker login -u $USERNAME -p $PASSWORD
    - docker tag caloriesmeter_back $USERNAME/$REPOSITORY:back
    - docker push $USERNAME/$REPOSITORY:back
    - docker tag caloriesmeter_front $USERNAME/$REPOSITORY:front
    - docker push $USERNAME/$REPOSITORY:front
  only:
    - master
